"""Added users, urls and comments tables

Revision ID: f7839842e7ee
Revises:
Create Date: 2022-01-24 23:57:52.100102

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f7839842e7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('user', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=False)
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('path', sa.String(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('url_id', sa.Integer(), nullable=True),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.Column('date', sa.Float(), nullable=True),
                    sa.Column('last', sa.BOOLEAN(), nullable=True),
                    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_comments_path'), 'comments', ['path'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_path'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
